### ISSUE TITLE
Run Failed on DJI Mavic 2 Enterprise Advanced

### ISSUE THREAD

**Issue by Phillweston** [The1only/rosettadrone#100]
**Describe the bug**
Using this APP on DJI mavic 2 enterprise advanced, app crash after running.

**To Reproduce**
I compiled and run this program on a dji mavic 2 enterprise advanced device, when launching the app, the aircraft can be detected.
Then I pressed Open Button, the app crashed immediately.

**Expected behavior**
Using android studio IDE, I found some error infomation on the logcat.
```
2022-01-11 14:10:01.900 2399-2399/sq.rogue.rosettadrone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sq.rogue.rosettadrone, PID: 2399
    java.lang.RuntimeException: Unable to start activity ComponentInfo{sq.rogue.rosettadrone/sq.rogue.rosettadrone.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void dji.sdk.flightcontroller.FlightController.setRollPitchControlMode(dji.common.flightcontroller.virtualstick.RollPitchControlMode)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2720)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:167)
        at android.app.ActivityThread.main(ActivityThread.java:6240)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1000)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void dji.sdk.flightcontroller.FlightController.setRollPitchControlMode(dji.common.flightcontroller.virtualstick.RollPitchControlMode)' on a null object reference
        at sq.rogue.rosettadrone.DroneModel.initFlightController(DroneModel.java:305)
        at sq.rogue.rosettadrone.DroneModel.<init>(DroneModel.java:258)
        at sq.rogue.rosettadrone.MainActivity.onCreate(MainActivity.java:756)
        at android.app.Activity.performCreate(Activity.java:6709)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2673)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2781) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1513) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:167) 
        at android.app.ActivityThread.main(ActivityThread.java:6240) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1000) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:868) 
```
 
**Screenshots**
![SAVE_20220111_145459](https://user-images.githubusercontent.com/42629755/148895606-fba56ee6-4aca-41d0-bf8c-84cada1d93a3.jpg)

**Smartphone (please complete the following information):**
 - Aircraft Device: DJI Mavic 2 Enterprise Advanced
 - Android Device: DJI Smart Controller

**Additional context**
Hopefully, the project will be able to add support for this model.

**Comment by Phillweston** [comment]
I have found the explanation in the DJI official repository issue list.
https://github.com/dji-sdk/Mobile-SDK-Android/issues/861

**Comment by kripper** [comment]
Please test latest version.
