### ISSUE TITLE
Crash at Runtime: Failed resolution of: Ldji/keysdk/callback/KeyListener

### ISSUE THREAD

**Issue by kylenietfeld** [The1only/rosettadrone#185]
### Describe the bug

I have implemented the keys.xml file in the values folder and the app successfully builds. However, it crashes instantly on my phone and I get the following error message. Any reason why?

19548-19548/sq.rogue.rosettadrone E/AndroidRuntime: FATAL EXCEPTION: main
    Process: sq.rogue.rosettadrone, PID: 19548
    java.lang.NoClassDefFoundError: **Failed resolution of: Ldji/keysdk/callback/KeyListener;**
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1367)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3741)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3996)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:237)
        at android.os.Looper.loop(Looper.java:335)
        at android.app.ActivityThread.main(ActivityThread.java:8140)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:579)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1050)
     **Caused by: java.lang.ClassNotFoundException: Didn't find class "dji.keysdk.callback.KeyListener" on path: DexPathList[[zip file "/data/app/~~mTSLaLEMvK7H_rpR0tOnlA==/sq.rogue.rosettadrone-**vQpHpBn2ZFJFQFht5i0ESQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~mTSLaLEMvK7H_rpR0tOnlA==/sq.rogue.rosettadrone-vQpHpBn2ZFJFQFht5i0ESQ==/lib/arm64, /data/app/~~mTSLaLEMvK7H_rpR0tOnlA==/sq.rogue.rosettadrone-vQpHpBn2ZFJFQFht5i0ESQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1367) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3741) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3996) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2450) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:237) 
        at android.os.Looper.loop(Looper.java:335) 
        at android.app.ActivityThread.main(ActivityThread.java:8140) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:579) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1050) 
2023-10-04 19:10:20.889 19548-19548/sq.rogue.rosettadrone W/FinalizerDaemon: type=1400 audit(0.0:3456): avc: denied { getopt } for path="/dev/socket/usap_pool_primary" scontext=u:r:untrusted_app:s0:c242,c256,c512,c768 tcontext=u:r:zygote:s0 tclass=unix_stream_socket permissive=0 app=sq.rogue.rosettadrone

### Screenshots

![Screenshot 2023-10-04 193115](https://github.com/RosettaDrone/rosettadrone/assets/77417229/658ab96a-f1f4-4273-815c-1a6be97d5517)

### Drone Model

```Markdown
Mavic2
```

### Smartphone Model

```Markdown
- Model: TCL430M
- Android version: 13
```

**Comment by kylenietfeld** [comment]
I got the app to work now. My problem was my antivirus software was blocking a few files.
